### ISSUE TITLE
Hardware shopping list

### ISSUE THREAD

**Issue by artivis** [Hypha-ROS/hypharos_minicar#1]
Hi, nice project !

Would it be possible for you to provide in this repo a complete hardware shopping list with links ??

Cheers.

**Comment by haochihlin** [comment]
Hi @artivis
Thanks for being interested in this project!
The package now is in beta version.
After final testing, we will release all details including the way to buy hardware.
(by the end of this month~)

**Comment by artivis** [comment]
Thanks for the quick answer.
That's great ! Looking forward to it.

Cheers.

**Comment by haochihlin** [comment]
Hi @artivis 
We have released reference of hardware shopping list.
Please find detail in readme file!.
Cheers

**Comment by artivis** [comment]
Awesome, thanks a bunch !
