### ISSUE TITLE
Problem about MPC parameters

### ISSUE THREAD

**Issue by Octalivia** [Hypha-ROS/hypharos_minicar#10]
I transplanted the MPC in this program to my program, but it cannot follow the path well. Is there a list of parameters available? I have tried the one in the param folder but it  left much to be desired

**Comment by haochihlin** [comment]
Hi @Octalivia ,
Sorry for the late reply. About the params for MPC tracking, if recall correctly, all of params could be defined via ROS params:  
[https://github.com/Hypha-ROS/hypharos_minicar/blob/master/launch/params/mpc/mpc_params.yaml](url).
If you want to find some internal states or modify the model, you could look into the MPC implementation source codes:
 [https://github.com/Hypha-ROS/hypharos_minicar/blob/master/src/MPC_Node.cpp](url)

**Comment by haochihlin** [comment]
update
