### ISSUE TITLE
error with cppad

### ISSUE THREAD

**Issue by 001SCH** [Hypha-ROS/hypharos_minicar#12]
Hi!, when I started the MPC_Node setting target point, the car could not start, and reported an error. I reinstalled ipopt several times according to the tutorial and it did not work. Do you know how to solve this problem:

cppad-20160000.1 error from a known source:
yq = f.Forward(q, xq): a zero order Taylor coefficient is nan.
Corresponding independent variables vector was written to binary a file.
vector_size = 158
file_name = /tmp/filer6SLLw
index = 82

Error detected by false result for
    if( CppAD::isnan( yq[ (q+1) * index + 0 ] )
at line 224 in the file
    /usr/include/cppad/local/forward.hpp
MPC_Node: /usr/include/cppad/utility/error_handler.hpp:207: static void CppAD::ErrorHandler::Default(bool, in
t, const char*, const char*, const char*): Assertion `false' failed.
[MPC_Node-6] process has died [pid 13466, exit code -6, cmd /home/sz/racecar/devel/lib/art_racecar/MPC_Node /
move_base_node/NavfnROS/plan:=/move_base/NavfnROS/plan __name:=MPC_Node __log:=/home/sz/.ros/log/78ff706a-a63
9-11e9-8c68-00e15c683339/MPC_Node-6.log].
log file: /home/sz/.ros/log/78ff706a-a639-11e9-8c68-00e15c683339/MPC_Node-6*.log

**Comment by haochihlin** [comment]
Hi @001SCH ,

I think for the issue of cppad, you should ask "COIN-OR" directly.
For testing, if you can not compile sucessfully on your environment, I suggest you use our released VirtualBox image first.

**Comment by mustang66ytz** [comment]
@001SCH I also encountered this issue when in my own MPC work. Have you figured out the fix to this  bug? I would appreciate so much on your help for this!

**Comment by Chuan701** [comment]
@haochihlin  @001SCH  @mustang66ytz 
Hello, everyone~
Do you have a solution now?     Thank you

**Comment by alperen-keser** [comment]
@Chuan701 @mustang66ytz @haochihlin @001SCH any updates on the issue? Have the same problem
