### ISSUE TITLE
about imu

### ISSUE THREAD

**Issue by ucmmesa** [Hypha-ROS/hypharos_minicar#13]
Hi,HaoChih,

Is the file minicar_imu_ekf_params.yaml available?

Best regards,

Jamson

**Comment by haochihlin** [comment]
Hi @ucmmesa ,

Unfortunately, I didn't keep the settings when I replaced my old laptop last year.

Cheers,
HaoChih, Lin

**Comment by ucmmesa** [comment]
Hi,Hao-Chih,

A bit pity to know that.

Best regards,
Jamson
________________________________
发件人: Hao-Chih, Lin <notifications@github.com>
发送时间: 2019年9月27日 8:14
收件人: Hypha-ROS/hypharos_minicar <hypharos_minicar@noreply.github.com>
抄送: ucmmesa <jianxin2013liu@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [Hypha-ROS/hypharos_minicar] about imu (#13)


Hi @ucmmesa<https://github.com/ucmmesa> ,

Unfortunately, I didn't keep the settings when I replaced my old laptop last year.

Cheers,
HaoChih, Lin

―
