### ISSUE TITLE
[MPC_Node-6] process has died 

### ISSUE THREAD

**Issue by sxxa-qlp** [Hypha-ROS/hypharos_minicar#15]
When i set "2D nav Gaol" in Rviz , occurs this error!
`cppad-20160000.1 error from a known source:
vector: index greater than or equal vector size
Error detected by false result for
    i < length_
at line 477 in the file 
    /usr/include/cppad/utility/vector.hpp
MPC_Node: /usr/include/cppad/utility/error_handler.hpp:207: static void CppAD::ErrorHandler::Default(bool, int, const char*, const char*, const char*): Assertion `false' failed.
[MPC_Node-6] process has died [pid 5762, exit code -6, cmd /home/qlp/catkin_ws/devel/lib/hypharos_minicar/MPC_Node __name:=MPC_Node __log:=/home/qlp/.ros/log/22928914-c330-11ea-98f8-000c29253a31/MPC_Node-6.log].
log file: /home/qlp/.ros/log/22928914-c330-11ea-98f8-000c29253a31/MPC_Node-6*.log
`

**Comment by sxxa-qlp** [comment]
According this file  _HyphaROS MiniCar (1/20 Scale MPC Racing Car)_，
IN _Install from source (16.04)_ -->_create your own catkin_ws_   --->` catkin_make`
it occurs some warning, may be this cause  `[MPC_Node-6] process has died` ? 
**Thanks for your reply!**

Scanning dependencies of target MPC_Node
Scanning dependencies of target Pure_Pursuit
[  5%] Building CXX object hypharos_minicar/CMakeFiles/Pure_Pursuit.dir/src/Pure_Pursuit.cpp.o
[ 11%] Building CXX object hypharos_minicar/CMakeFiles/MPC_Node.dir/src/MPC.cpp.o
[ 17%] Linking CXX executable /home/qlp/catkin_ws/devel/lib/hypharos_minicar/Pure_Pursuit
[ 17%] Built target Pure_Pursuit
Scanning dependencies of target ydlidar_node
[ 23%] Building CXX object ydlidar/CMakeFiles/ydlidar_node.dir/src/ydlidar_node.cpp.o
In file included from /home/qlp/catkin_ws/src/ydlidar/sdk/include/ydlidar_driver.h:10:0,
                 from /home/qlp/catkin_ws/src/ydlidar/sdk/include/CYdLidar.h:4,
                 from /home/qlp/catkin_ws/src/ydlidar/src/ydlidar_node.cpp:12:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::show(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:40:20: warning: format not a string literal and no format arguments [-Wformat-security]
         printf (out);
                    ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::message(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:53:18: warning: format not a string literal and no format arguments [-Wformat-security]
       printf (out);
                  ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::warning(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:69:18: warning: format not a string literal and no format arguments [-Wformat-security]
       printf (out);
                  ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::error(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:85:18: warning: format not a string literal and no format arguments [-Wformat-security]
       printf (out);
                  ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::debug(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:104:20: warning: format not a string literal and no format arguments [-Wformat-security]
         printf (out);
                    ^
[ 29%] Building CXX object ydlidar/CMakeFiles/ydlidar_node.dir/sdk/src/impl/unix/unix_timer.cpp.o
[ 35%] Building CXX object ydlidar/CMakeFiles/ydlidar_node.dir/sdk/src/impl/unix/unix_serial.cpp.o
[ 41%] Building CXX object ydlidar/CMakeFiles/ydlidar_node.dir/sdk/src/impl/unix/list_ports_linux.cpp.o
[ 47%] Building CXX object ydlidar/CMakeFiles/ydlidar_node.dir/sdk/src/ydlidar_driver.cpp.o
In file included from /home/qlp/catkin_ws/src/ydlidar/sdk/src/common.h:17:0,
                 from /home/qlp/catkin_ws/src/ydlidar/sdk/src/ydlidar_driver.cpp:9:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::show(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:40:20: warning: format not a string literal and no format arguments [-Wformat-security]
         printf (out);
                    ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::message(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:53:18: warning: format not a string literal and no format arguments [-Wformat-security]
       printf (out);
                  ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::warning(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:69:18: warning: format not a string literal and no format arguments [-Wformat-security]
       printf (out);
                  ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::error(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:85:18: warning: format not a string literal and no format arguments [-Wformat-security]
       printf (out);
                  ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::debug(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:104:20: warning: format not a string literal and no format arguments [-Wformat-security]
         printf (out);
                    ^
[ 52%] Building CXX object ydlidar/CMakeFiles/ydlidar_node.dir/sdk/src/Console.cpp.o
[ 58%] Building CXX object hypharos_minicar/CMakeFiles/MPC_Node.dir/src/MPC_Node.cpp.o
In file included from /home/qlp/catkin_ws/src/ydlidar/sdk/src/Console.cpp:1:0:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::show(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:40:20: warning: format not a string literal and no format arguments [-Wformat-security]
         printf (out);
                    ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::message(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:53:18: warning: format not a string literal and no format arguments [-Wformat-security]
       printf (out);
                  ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::warning(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:69:18: warning: format not a string literal and no format arguments [-Wformat-security]
       printf (out);
                  ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::error(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:85:18: warning: format not a string literal and no format arguments [-Wformat-security]
       printf (out);
                  ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::debug(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:104:20: warning: format not a string literal and no format arguments [-Wformat-security]
         printf (out);
                    ^
[ 64%] Building CXX object ydlidar/CMakeFiles/ydlidar_node.dir/sdk/src/serial.cpp.o
In file included from /home/qlp/catkin_ws/src/ydlidar/sdk/src/common.h:17:0,
                 from /home/qlp/catkin_ws/src/ydlidar/sdk/src/serial.cpp:12:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::show(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:40:20: warning: format not a string literal and no format arguments [-Wformat-security]
         printf (out);
                    ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::message(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:53:18: warning: format not a string literal and no format arguments [-Wformat-security]
       printf (out);
                  ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::warning(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:69:18: warning: format not a string literal and no format arguments [-Wformat-security]
       printf (out);
                  ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::error(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:85:18: warning: format not a string literal and no format arguments [-Wformat-security]
       printf (out);
                  ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::debug(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:104:20: warning: format not a string literal and no format arguments [-Wformat-security]
         printf (out);
                    ^
[ 70%] Building CXX object ydlidar/CMakeFiles/ydlidar_node.dir/sdk/src/CYdLidar.cpp.o
In file included from /home/qlp/catkin_ws/src/ydlidar/sdk/include/ydlidar_driver.h:10:0,
                 from /home/qlp/catkin_ws/src/ydlidar/sdk/include/CYdLidar.h:4,
                 from /home/qlp/catkin_ws/src/ydlidar/sdk/src/CYdLidar.cpp:1:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::show(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:40:20: warning: format not a string literal and no format arguments [-Wformat-security]
         printf (out);
                    ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::message(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:53:18: warning: format not a string literal and no format arguments [-Wformat-security]
       printf (out);
                  ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::warning(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:69:18: warning: format not a string literal and no format arguments [-Wformat-security]
       printf (out);
                  ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::error(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:85:18: warning: format not a string literal and no format arguments [-Wformat-security]
       printf (out);
                  ^
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h: In member function ‘void ydlidar::Console::debug(const char*, ...)’:
/home/qlp/catkin_ws/src/ydlidar/sdk/include/Console.h:104:20: warning: format not a string literal and no format arguments [-Wformat-security]
         printf (out);
                    ^
[ 76%] Building C object ydlidar/CMakeFiles/ydlidar_node.dir/sdk/src/lock.c.o
[ 82%] Linking CXX executable /home/qlp/catkin_ws/devel/lib/ydlidar/ydlidar_node
[ 82%] Built target ydlidar_node
Scanning dependencies of target ydlidar_client
[ 88%] Building CXX object ydlidar/CMakeFiles/ydlidar_client.dir/src/ydlidar_client.cpp.o
[ 94%] Linking CXX executable /home/qlp/catkin_ws/devel/lib/ydlidar/ydlidar_client
[ 94%] Built target ydlidar_client
[100%] Linking CXX executable /home/qlp/catkin_ws/devel/lib/hypharos_minicar/MPC_Node
[100%] Built target MPC_Node

**Comment by sxxa-qlp** [comment]
There is no effective way!
i will try reinstall ubuntu and ros....

**Comment by Curiosi-Orch** [comment]
> There is no effective way!
> i will try reinstall ubuntu and ros....

I was faced with same problem as you do. You can just reinstall ipopt to solve the problem. Remember to follow the steps in the doc file of this very package.
