### ISSUE TITLE
fatal error: ackermann_msgs/AckermannDriveStamped.h: No such file or directory  

### ISSUE THREAD

**Issue by fighterxi** [Hypha-ROS/hypharos_minicar#2]
Hello , sorry to trouble you ，I found this problem when I performed the fourth step（catkin_make ）. It maybe caused by the lack of some files called "ackermann_msgs"?

___________
"/home/rosfun/catkin_s0/src/hypharos_minicar-master/src/MPC_Node.cpp:30:50: fatal error: ackermann_msgs/AckermannDriveStamped.h: No such file or directory
compilation terminated.
hypharos_minicar-master/CMakeFiles/MPC_Node.dir/build.make:86: recipe for target 'hypharos_minicar-master/CMakeFiles/MPC_Node.dir/src/MPC_Node.cpp.o' failed
make[2]: *** [hypharos_minicar-master/CMakeFiles/MPC_Node.dir/src/MPC_Node.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:3578: recipe for target 'hypharos_minicar-master/CMakeFiles/MPC_Node.dir/all' failed
make[1]: *** [hypharos_minicar-master/CMakeFiles/MPC_Node.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j2 -l2" failed
"

**Comment by haochihlin** [comment]
Hi @fighterxi 
Yes, as you described, you need to install "ros-kinetic-ackermann-msgs" in advance.
I have updated readme, thanks!
