### ISSUE TITLE
 error  with cppad when performing stage simulation

### ISSUE THREAD

**Issue by fighterxi** [Hypha-ROS/hypharos_minicar#3]
Sorry to disturb you again, I found this problem when I performed the  "roslaunch hypharos_minicar HyphaROS_Simulation_Stage.launch". How can I solve this problem?  
The following is the error messages. Looking forward to your reply.

__________________________
[ INFO] [1533086166.443847298, 1.900000000]: Sim period is set to 0.05
[ WARN] [1533086166.450000414, 1.900000000]: Trajectory Rollout planner initialized with param meter_scoring not set. Set it to true to make your settins robust against changes of costmap resolution.
[ INFO] [1533086167.457398235, 2.900000000]: Recovery behavior will clear layer obstacles
[ INFO] [1533086167.477806223, 2.900000000]: Recovery behavior will clear layer obstacles
[ INFO] [1533086167.529405802, 2.900000000]: odom received!
[ INFO] [1533086170.146098347, 5.600000000]: Goal Received !
cppad-20160000.1 error from a known source:
vector: index greater than or equal vector size
Error detected by false result for
    i < length_
at line 477 in the file 
    /usr/include/cppad/utility/vector.hpp
MPC_Node: /usr/include/cppad/utility/error_handler.hpp:207: static void CppAD::ErrorHandler::Default(bool, int, const char*, const char*, const char*): Assertion `false' failed.
[MPC_Node-6] process has died [pid 19202, exit code -6, cmd /home/rosfun/catkin_s0/devel/lib/hypharos_minicar/MPC_Node __name:=MPC_Node __log:=/home/rosfun/.ros/log/7576e14e-9528-11e8-bf85-000c291e5aed/MPC_Node-6.log].
log file: /home/rosfun/.ros/log/7576e14e-9528-11e8-bf85-000c291e5aed/MPC_Node-6*.log

**Comment by haochihlin** [comment]
Hi @fighterxi 
Sorry for the late reply.
I think the cause of your problem came from "CppAD",
it depends on how you install & link your ipopt solver.
(ref: https://github.com/udacity/sdc-issue-reports/issues/827)
So, it is hard for me to help you in this situation.
However, I will release virtual box image recently, so in this case, you can test our simulation on it.

**Comment by fighterxi** [comment]
Hi @jim1993 ， thank you for your reply, I reinstalled Ipopt, and no longer have the above problems.

**Comment by aogrcs** [comment]
@fighterxi Hi, could you tell me how to install Ipopt? Thanks

**Comment by haopo2005** [comment]
> @fighterxi Hi, could you tell me how to install Ipopt? Thanks

you may refer this:
[https://github.com/udacity/CarND-MPC-Quizzes/blob/master/install_ipopt.sh](https://github.com/udacity/CarND-MPC-Quizzes/blob/master/install_ipopt.sh)

**Comment by fighterxi** [comment]
@aogrcs   Hi,  sorry for the late reply. I followed this "  hypharos_minicar/document/ipopt_install/ipopt_x86_install_tutorial.md." to install  Ipopt .
