### ISSUE TITLE
關於minicar和minibot選擇，以及通訊問題。

### ISSUE THREAD

**Issue by LagrangeWang** [Hypha-ROS/hypharos_minicar#4]
你好，林老師。我想請教，minicar比minibot的功能多一些，這些功能也能夠在minibot上實現嗎。
另外小車的在線建圖功能是在PC上演示，樹莓派或Odroid是作為中間通訊媒介嗎。

**Comment by haochihlin** [comment]
Sorry for the late reply (I just moved to another country ~)
About your question, conceptually, the purpose of minicar and minibot are different.
The main target of minibot is to create the lowest platform for lidar based moving platform.
In contrast, minicar is to demonstrate different control algorithms (like pure-pursuit and MPC)
So, for the minibot, it is quite hard for this platform to adopt the algorithms presented on minicar
(the computing resource of Pi3 is too low to handle optimization solving processing)

For the mapping demo, in both minicar and minibot are running onboard.
However, we also recommend people to use rosbag and do the mapping offline to get better result!

**Comment by haochihlin** [comment]
I supposed this issue has been solved.

**Comment by LagrangeWang** [comment]
thank you
