### ISSUE TITLE
請問關於ORDROID XU4的配件模塊問題。

### ISSUE THREAD

**Issue by LagrangeWang** [Hypha-ROS/hypharos_minicar#6]
你好，我了解到這塊板是不包含SD卡、EMMC模塊、WIFI、藍牙。
SD卡購買16GB的應該足夠。WIFI和藍牙，在淘寶上看到ODROID官方的WIFI模塊比較貴唉。我想只要是Ubuntu能驅動的，比如Realtek的RTL8192這款，在筆電Ubuntu16.04下測試能用，那麼請問也能用在ODROID XU4上面吧。
另外在購買底盤的店鋪，賣家有提供藍牙模塊方案，那麼STM32板上有必要安裝藍牙模塊嗎。

**Comment by haochihlin** [comment]
你好
Odroid部分: 
SD 16G即可
Wifi dongle比較麻煩, 會跟你選用的odroid img有關, 同一支wifi dongle在某個img下kernel有支援, 但另一種img沒有, 你也可以自己下載kernel driver, 但我試過的穩定性不佳, 所以我後來都是買官網的wifi dongle 3的樣子

車子底盤部分:
我是選STM32 (不含bluetooth or ps2把手)

**Comment by LagrangeWang** [comment]
非常感謝您的解答
