### ISSUE TITLE
Connection 

### ISSUE THREAD

**Issue by swapda** [Hypha-ROS/hypharos_minicar#7]
Hi @haochihlin 
can you share "component connection" figures or images of how you have assembled all hardware of minicar, like you shared a Tutorial pdf file for hyphaROS racecar which contains images of connection of hardware.
Thanks

**Comment by haochihlin** [comment]
Hi @swapda 
Thank you for being interested in this repo.
About the document, I agree, but this is non-profit side project without financial support.
So, I will find some time to do it, however, I can not guarantee when it will be done.

Cheers
