### ISSUE TITLE
關於WIFI模組問題

### ISSUE THREAD

**Issue by LagrangeWang** [Hypha-ROS/hypharos_minicar#8]
您在之前提到的WIFI MODULE 3是指的wifi dongle 3嗎？這款WIFI採用RTL8188CUS，所以XU4的鏡像文件包含了編譯過的RTL8188CUS驅動。
如果我使用一款同樣使用RTL8188CUS的WIFI MODULE，也是能夠適用的嗎，目前不太方便購買wifi dongle 3。謝謝。

**Comment by haochihlin** [comment]
你好
是的, 是指wifi dongle 3.
可以用相同晶片的wifi, 我們有確實有幾台就不是用原廠的,
但要注意晶片編號RTL8188 好像只有CUS版本可以  其他的你要去odroid官網確認
真的不行也可以自己下載driver安裝, 但不保證穩定性就是了
