### ISSUE TITLE
請問ODROID與STM32連接問題

### ISSUE THREAD

**Issue by LagrangeWang** [Hypha-ROS/hypharos_minicar#9]
請問，用軟體和硬體實現STM32與ODROID的通訊。依據該檔案下STM32代碼，是用一塊USB轉TTL模組，一端連接ODROID的USB口，另一端RX,TX,GND,5V這4隻線連接STM32的USART口嗎？
謝謝您的幫助

**Comment by haochihlin** [comment]
你好
STM32部分我不太熟 主要是用廠商給的sample code稍稍消改
所以可能要請你直接向廠商詢問

**Comment by LagrangeWang** [comment]
謝謝，我有買到一套同樣的模塊，並將PURECODE下的HEX燒錄僅STM32，然後啟Desktop_Mapping.launch，按下鍵盤的JKLI控制鍵電機冇有轉動
